git-debimport xorg-server_1.12.4-6+deb7u1.diff.gz

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -7,20 +7,34 @@
 # Uncomment this to turn on verbose mode.
 #export DH_VERBOSE=1
 
-include debian/xsfbs/xsfbs.mk
+# Set up the $(STAMP_DIR) directory, and use it for quilt' stamp:
+STAMP_DIR     := stampdir
+QUILT_STAMPFN := $(STAMP_DIR)/patch
+$(STAMP_DIR)/stampdir:
+	mkdir $(STAMP_DIR)
+	>$@
 
+include /usr/share/quilt/quilt.make
+
+# we don't have a good way to check for dpkg-dev version, so use presence of
+# buildflags.mk as a substitute.
+ifneq (,$(wildcard /usr/share/dpkg/buildflags.mk))
+vars = $(shell DEB_BUILD_MAINT_OPTIONS="hardening=+pie" DEB_LDFLAGS_MAINT_APPEND="-Wl,-Bsymbolic" DEB_CPPFLAGS_MAINT_APPEND="-DPRE_RELEASE=0" dpkg-buildflags --export=configure)
+else
 CFLAGS = -Wall -g
 ifneq (,$(filter noopt,$(DEB_BUILD_OPTIONS)))
 	CFLAGS += -O0
 else
 	CFLAGS += -O2
 endif
+CPPFLAGS = -DPRE_RELEASE=0
+vars = CFLAGS="$(CFLAGS)" CPPFLAGS="$(CPPFLAGS)"
+endif
+
 ifneq (,$(filter parallel=%,$(DEB_BUILD_OPTIONS)))
 	NUMJOBS = $(patsubst parallel=%,%,$(filter parallel=%,$(DEB_BUILD_OPTIONS)))
 	MAKEFLAGS += -j$(NUMJOBS)
 endif
-
-CPPFLAGS += -DPRE_RELEASE=0
 
 DEB_HOST_ARCH      ?= $(shell dpkg-architecture -qDEB_HOST_ARCH)
 DEB_HOST_GNU_TYPE  ?= $(shell dpkg-architecture -qDEB_HOST_GNU_TYPE)
@@ -47,7 +61,6 @@ endif
 ifeq ($(DEB_HOST_ARCH_OS), linux)
 	build_xfbdev = --enable-xfbdev
 	selinux = --enable-xselinux
-	xkbrules = --with-default-xkb-rules=evdev
 else
 	build_xfbdev = --disable-xfbdev
 	selinux = --disable-xselinux
@@ -63,7 +76,10 @@ config_backend = --disable-config-dbus
 ifeq ($(DEB_HOST_ARCH_OS), linux)
 	config_backend += --enable-config-udev --disable-config-hal
 else ifeq ($(DEB_HOST_ARCH_OS), kfreebsd)
-	config_backend += --disable-config-udev --enable-config-hal
+	config_backend += --disable-config-udev
+	config_backend_main += --enable-config-hal
+	config_backend_udeb += --disable-config-hal
+	libs = LIBS=-lbsd
 else # hurd
 	config_backend += --disable-config-udev --disable-config-hal
 endif
@@ -78,14 +94,17 @@ INSTALL=/usr/bin/install
 
 VENDOR = $(shell lsb_release -i -s)
 
-BUILDER=$(shell dpkg-parsechangelog | awk -F': ' '/^Maintainer: / {print $$2}')
+SOURCE_NAME    :=  xorg-server
+SOURCE_VERSION := $(shell dpkg-parsechangelog | awk -F': ' '/^Version: / {print $$2}')
+BUILDER        := $(shell dpkg-parsechangelog | awk -F': ' '/^Maintainer: / {print $$2}')
 
 # disable-static is so we don't get libfoo.a for modules.  now if only we could
 # kill the .las.
 confflags += \
+	     --disable-silent-rules \
 	     --disable-static \
 	     --without-dtrace \
-	     --disable-werror \
+	     --disable-strict-compilation \
 	     --disable-debug \
 	     $(config_tests) \
 	     --with-int10=x86emu \
@@ -93,16 +112,13 @@ confflags += \
 	     --with-builderstring="$(SOURCE_NAME) $(SOURCE_VERSION) ($(BUILDER))" \
 	     --with-xkb-path=/usr/share/X11/xkb \
 	     --with-xkb-output=/var/lib/xkb \
-	     $(xkbrules) \
 	     --disable-builddocs \
 	     --disable-install-libxf86config \
-	     --disable-null-root-cursor \
 	     --enable-mitshm \
 	     --enable-xres \
 	     --disable-xcsecurity \
 	     --disable-xcalibrate \
 	     --disable-tslib \
-	     --disable-multibuffer \
 	     --enable-dbe \
 	     --disable-xf86bigfont \
 	     --enable-dpms \
@@ -110,9 +126,9 @@ confflags += \
 	     --enable-xorg \
 	     --disable-xquartz \
 	     --disable-xwin \
-	     --disable-xsdl \
 	     --disable-xfake \
-	     --disable-install-setuid
+	     --disable-install-setuid \
+	     $(libs)
 
 confflags_main = \
 	--with-default-font-path="/usr/share/fonts/X11/misc,/usr/share/fonts/X11/cyrillic,/usr/share/fonts/X11/100dpi/:unscaled,/usr/share/fonts/X11/75dpi/:unscaled,/usr/share/fonts/X11/Type1,/usr/share/fonts/X11/100dpi,/usr/share/fonts/X11/75dpi,/var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType,built-ins" \
@@ -142,6 +158,7 @@ confflags_main = \
 	$(build_xfbdev) \
 	--with-sha1=libgcrypt \
 	--enable-xcsecurity \
+	$(config_backend_main) \
 	$(void)
 
 confflags_udeb = \
@@ -171,10 +188,13 @@ confflags_udeb = \
 	--disable-kdrive \
 	--disable-xephyr \
 	--disable-xfbdev \
-	--with-sha1=libnettle \
+	--with-sha1=nettle \
+	$(config_backend_udeb) \
 	$(void)
 
-$(STAMP_DIR)/autoreconf: $(STAMP_DIR)/patch
+$(QUILT_STAMPFN): $(STAMP_DIR)/stampdir
+
+$(STAMP_DIR)/autoreconf: $(STAMP_DIR)/stampdir $(QUILT_STAMPFN)
 	dh_testdir
 	autoreconf -vfi
 	>$@
@@ -191,8 +211,7 @@ $(STAMP_DIR)/configure-%: $(STAMP_DIR)/autoreconf
 	  --localstatedir=/var \
 	  $(confflags) \
 	  $(confflags_$*) \
-	  CFLAGS="$(CFLAGS)" \
-	  CPPFLAGS="$(CPPFLAGS)"
+	  $(vars)
 	>$@
 
 $(STAMP_DIR)/build-%: $(STAMP_DIR)/configure-%
@@ -210,11 +229,13 @@ ifeq ($(udeb), yes)
 build: $(STAMP_DIR)/build-udeb
 build: $(STAMP_DIR)/tests-udeb
 endif
+build-arch: build
+build-indep: build
 
-clean: xsfclean
+clean: unpatch abibumpcheck
 	dh_testdir
-	dh_testroot
-	
+
+	rm -rf $(STAMP_DIR)
 	rm -f config.cache config.log config.status
 	rm -f */config.cache */config.log */config.status
 	rm -f conftest* */conftest*
@@ -225,31 +246,31 @@ clean: xsfclean
 	rm -f include/do-not-use-config.h.in
 	rm -f m4/lt*.m4 m4/libtool.m4
 	find -name Makefile.in -delete
-	
+
 	dh_clean
 
 install: build
 	dh_testdir
 	dh_testroot
-	dh_clean -k
+	dh_prep
 	dh_installdirs
-	
+
 	cd build-main && $(MAKE) DESTDIR=$(CURDIR)/debian/tmp/main install
 ifeq ($(udeb), yes)
 	cd build-udeb && $(MAKE) DESTDIR=$(CURDIR)/debian/tmp/udeb install
 endif
-	
+
 	# oh, yuck.
 	find debian/tmp/*/usr/lib/xorg -type f -name '*.la' | \
 	  xargs rm -f
-	
+
 	# remove modules not needed in d-i
 	rm -rf debian/tmp/udeb/usr/lib/xorg/modules/multimedia
 	rm -f debian/tmp/udeb/usr/lib/xorg/modules/libxaa.so
 	rm -f debian/tmp/udeb/usr/lib/xorg/modules/libexa.so
 	rm -f debian/tmp/udeb/usr/lib/xorg/modules/libwfb.so
 	rm -f debian/tmp/udeb/usr/lib/xorg/modules/libxf8_16bpp.so
-	
+
 	install -m 755 debian/local/xvfb-run debian/tmp/main/usr/bin
 	install debian/local/xvfb-run.1 debian/tmp/main/usr/share/man/man1
 ifneq ($(DEB_HOST_ARCH_OS), linux)
@@ -268,6 +289,7 @@ binary-initial:
 
 # stub to build deb files, used by binary-indep and binary-arch
 binary-deb:
+	dh_lintian
 	dh_compress
 	dh_fixperms
 	dh_installdeb
@@ -276,30 +298,46 @@ binary-deb:
 	dh_md5sums
 	dh_builddeb
 
-serverminver = $(shell cat debian/serverminver)
+# Only read the first line, the rest of the file is used to determine
+# when the minimal version as to be bumped:
+SERVERMINVER = debian/serverminver
+serverminver = $(shell head -1 $(SERVERMINVER))
+
+.PHONY: abibumpcheck
+abibumpcheck: debian/serverminver
+	@echo Checking for the need of an ABI bump
+	# Build an updated version of the file:
+	head -1 $(SERVERMINVER) > $(SERVERMINVER).new
+	perl -ne 'print "$$1:$$2.$$3\n" if /^#define\s+(ABI_(?:VIDEODRV|XINPUT)_VERSION)\s+SET_ABI_VERSION\(\s*(\d+)\s*,\s*(\d+)\s*\)/' hw/xfree86/common/xf86Module.h|sort >> $(SERVERMINVER).new
+	# Compare both files:
+	@if ! cmp --quiet $(SERVERMINVER) $(SERVERMINVER).new; then \
+	echo "serverminver bump required, ABI changed!";\
+	diff -u $(SERVERMINVER) $(SERVERMINVER).new; \
+	exit 1; \
+	else \
+	echo "ABI unchanged"; \
+	rm -f $(SERVERMINVER).new; \
+	fi
 
 # Build architecture-dependent files here.
 binary-arch: build install
 	$(MAKE) -f debian/rules DH_OPTIONS=-s binary-initial
-	
+
 	dh_installdocs -s
-	dh_installchangelogs -s ChangeLog
+	dh_installchangelogs -s
 	dh_install $(DH_INSTALL_OPTIONS) -s --sourcedir=debian/tmp --list-missing
 	$(INSTALL) -d $(CURDIR)/debian/xserver-xorg-dev/usr/share/xserver-xorg
-	# XXX might want to only extract the major ABI versions?
-	abi_videodrv=`PKG_CONFIG_PATH=debian/tmp/main/usr/lib/pkgconfig pkg-config --variable=abi_videodrv xorg-server`; \
+	# Extract only the major ABI version:
+	abi_videodrv=`PKG_CONFIG_PATH=debian/tmp/main/usr/lib/pkgconfig pkg-config --variable=abi_videodrv xorg-server|cut -d . -f 1`; \
 	echo videoabi=xorg-video-abi-$$abi_videodrv > debian/xserver-xorg-core.substvars && \
 	echo "xorg-video-abi-$$abi_videodrv, xserver-xorg-core (>= $(serverminver))" > debian/xserver-xorg-dev/usr/share/xserver-xorg/videodrvdep
-	abi_xinput=`PKG_CONFIG_PATH=debian/tmp/main/usr/lib/pkgconfig pkg-config --variable=abi_xinput xorg-server`; \
+	abi_xinput=`PKG_CONFIG_PATH=debian/tmp/main/usr/lib/pkgconfig pkg-config --variable=abi_xinput xorg-server|cut -d . -f 1`; \
 	echo inputabi=xorg-input-abi-$$abi_xinput >> debian/xserver-xorg-core.substvars && \
 	echo "xorg-input-abi-$$abi_xinput, xserver-xorg-core (>= $(serverminver))" > debian/xserver-xorg-dev/usr/share/xserver-xorg/xinputdep
 
-	$(INSTALL) -m644 $(CURDIR)/debian/videoabiver \
-	           $(CURDIR)/debian/xserver-xorg-dev/usr/share/xserver-xorg/videoabiver
-	$(INSTALL) -m644 $(CURDIR)/debian/inputabiver \
-	           $(CURDIR)/debian/xserver-xorg-dev/usr/share/xserver-xorg/inputabiver
-	$(INSTALL) -m644 $(CURDIR)/debian/serverminver \
-	           $(CURDIR)/debian/xserver-xorg-dev/usr/share/xserver-xorg/serverminver
+	# The udeb uses the same substvars:
+	cp debian/xserver-xorg-core.substvars debian/xserver-xorg-core-udeb.substvars
+
 	$(INSTALL) -m 755 -d debian/xserver-xorg-core/usr/share/bug/xserver-xorg-core
 	$(INSTALL) -m 755 debian/xserver-xorg-core.bug.script debian/xserver-xorg-core/usr/share/bug/xserver-xorg-core/script
 ifeq ($(DEB_HOST_ARCH_OS), linux)
@@ -314,7 +352,7 @@ endif
 	dh_installman -s
 	dh_link -s
 	dh_strip -pxserver-xorg-core --dbg-package=xserver-xorg-core-dbg
-	dh_strip -s --remaining-packages
+	dh_strip -s -Nxserver-xorg-core -Nxserver-xorg-core-dbg
 	$(MAKE) -f debian/rules DH_OPTIONS=-s binary-deb
 
 
@@ -323,7 +361,7 @@ binary-indep: build install
 	$(MAKE) -f debian/rules DH_OPTIONS=-i binary-initial
 	dh_install -i --sourcedir=debian/tmp
 	dh_installdocs -i
-	dh_installchangelogs -i
+	dh_installchangelogs -i ChangeLog
 
 	$(MAKE) -f debian/rules DH_OPTIONS=-i binary-deb
 
